### ISSUE TITLE
Cloud Storage issue with Offcloud

### ISSUE THREAD

**Issue by Blockr22** [kodifitzwell/repo#1]
Hey Dev, so i tried accessing files that i stored in Offcloud cloud storage in POV cloud storage section. but when i click on the file, in my case its a series with 10 episodes. instead of it behaving like a folder and asking for me which episode i would like to play, it just behaves like a file that plays automatically when i press once and play without video, only can hear audio and it becomes 60 hours of playback file. 
u can check my issue in this screen recording.
https://file.io/HQZ9llRfxvoB

**Comment by Blockr22** [comment]
https://file.io/rzpMidqhmdS0

Yes, i can explore just fine. There were no cached links for this series & i m trying to cache all the seasons. So that i can watch later, offcloud caching is painfully slow. Anyways, there’s no issue when i search the show simple from POV. There’s issues when i access it from POV cloud storage options. My reason of using this option is sometimes when i watch some anime’s & POV or FEN don’t find any sources even if it’s cached. So then i use this cloud storage option to access my files store in cloud. But with POV & offcloud it’s not working as intended. If u have Offcloud subscription u can cache any series with multiple episodes & try to watch it from cloud storage section of POV or have a look at above video with the link

**Comment by kodifitzwell** [comment]
> POV & offcloud it’s not working as intended.

wrong.  it's working exactly as intended.  in the screenshots I posted the torrent contains mutiple files and is correctly listed as a folder.  that s03 you got from where ever is clearly a zip file (as indicated by OC).  for "single file torrents" the cloud storage in POV lists it as a file because that's what OC tells POV it is.  why kodi is trying to play it is for the kodi forums.
![capture](https://github.com/kodifitzwell/repo/assets/105136042/7820a9c2-739a-4ed7-a7f7-8672eb6dda06)

I can't speak for anime, but for shows, in the future when you find a cached torrents through POV, from the context menu select "add to cloud" to save it for later viewing and it should add it correctly to your user cloud to view as you intended.
![addtocloud](https://github.com/kodifitzwell/repo/assets/105136042/9281efc6-6d6e-40fe-bc1c-43d4254a76c2)

if you pull a rando torrent from the web and add it to OC, make sure the torrent contains the source files and is not a torrent of one zip file that needs to be extracted.

> when i watch some anime’s & POV or FEN don’t find any sources even if it’s cached.

if neither addon finds sources, how are you sure it is "cached?"

**Comment by Blockr22** [comment]
Kk, got it. I understand, only adding torrents with pov works & it shouldn’t be zip file. Thnx
