### ISSUE TITLE
Trakt issue

### ISSUE THREAD

**Issue by sasagr** [kodifitzwell/repo#10]
I m not managing to get Trakt integration working. Also authorized services keep on getting revoked. I don’t have such issues with Fen if this can help. Here a log
https://paste.kodi.tv/utawahuguv

**Comment by kodifitzwell** [comment]
```
2024-03-24 11:49:13.035 T:1044976    info <general>: >> POV <<: TraktMonitor Service Update POV TraktMonitor - Aborted. No Trakt Account Active - Next Update in 30 minutes...
2024-03-24 11:52:38.273 T:1044833    info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-03-24 11:53:58.262 T:1045658    info <general>: >> trakt error <<: 401 Client Error: Unauthorized for url: https://api.trakt.tv/sync/last_activities
```

here it looks like you try to authorize trakt (about ~80 secs for the window to pop, website auth, etc), then when the addon trys to sync data trakt is saying you're not authorized.  when you authorize does your username populate?

I can only recommend that you go to Trakt in addon settings and reset to "Defaults" for that category.  be sure to select "OK" button in window (not remote). go to the cache menu and clear all cache.  then go back to Trakt in addon settings, only authorize and **select "OK" button in window after**, do not change any other settings.

> Also authorized services keep on getting revoked.

is this for debrid as well as trakt?  like immediately or after some time?  if true, very suspicious it would seem as if something is affecting your `settings.xml` file.  but then all your settings should be affected/reverted.

I don't have such issues with windows/libreelec(linux).  but there is no os specific code so idk why you have such trouble with tvos.

if that doesn't work, I don't have an apple device to test on, so the only thing I could do is ask you to install a zip file of the addon with extra-extra logging code to see where the issue is being created.

**Comment by sasagr** [comment]
I eventually did a new fresh kodi install of 20.5 and installed only POV and all seems to be working fine. So it must have been a conflict with some other addon. Thanks for your time and I hope you will keep up with this good work!
