### ISSUE TITLE
POV feature request - Dolby Vision on top

### ISSUE THREAD

**Issue by djdirty60** [kodifitzwell/repo#13]
Good day,

Is it perhaps possible to add an option that Dolby vision results will be at the top and then HDR etc etc? Like 4K, 1080, 720. And maybe also for the audio types atmos, dts-x etc etc

Thank you in advance

**Comment by kodifitzwell** [comment]
good day to you,

I assume this is partially because other addons offer this.  just so it doesn't come off as being a dismissive, understand that while my tvs are 4k etc. the aged htpcs I use are only capable of 1080, so all the diff video/audio formats do not concern me too much.

help me understand better the difference you are seeking.

take movie like mission impossible sorted by size/quality. 18 of the 21 4k results have some permutation of DV/HDR.
![mi](https://github.com/kodifitzwell/repo/assets/105136042/3a981864-4e3e-4ca1-b5ad-3b2461f40d29)

okay lets take another one like immaculate.  the third result is labeled HDR and the first one may or may not be as there is no way to tell from the label.
![im](https://github.com/kodifitzwell/repo/assets/105136042/a716dad8-1082-4c89-8f10-60227090f175)

what are your sort options/filters such that DV/HDR/etc are not already within the top few results?

point is the list is already sorted a few times for the few filters included.  for each feature your asking for in DV/HDR/ATMOS/etc there is another sort of some sort.  while the cpu time is probably not significant, is there really a point to continally sorting if by and large the results will vary very little?

**Comment by djdirty60** [comment]
Good day,

Thanks for your comment, is mainly for series that support dolby vision and atmos. And I have it on automatically search the next episode and one time you get sdr and then HDR and then dolby vision. Would be nice if that's just the same type of file every time. And then I can also have movie automatically chosen.

Thank you in advance

**Comment by djdirty60** [comment]
Sorry me wrong, overlooked.

Consider as not posted
