### ISSUE TITLE
POV changelog.txt

### ISSUE THREAD

**Issue by TheGuru276** [kodifitzwell/repo#14]
Hello,

Don't know if you bother trying to keep the change log updated with every release but for a little while now when I view the change log within the add-on it seems to have one for 4.05.01 at the very top, with the next log entry being 4.04.01, even though the current release seems to only be 4.04.16

**Comment by kodifitzwell** [comment]
most of the few updates have been a line or two addition or reversion so I haven't really bothered to update the changelog.

I'm using dates as version numbers so on or around 24 May 1, I'll push an update and the changelog will include everything up to that version in one changelog entry instead of multiple one or two line per version entries.

**Comment by TheGuru276** [comment]
Ok. Thanks
