### ISSUE TITLE
Feature request - UpNext Episode (Next Episode Pop Up)

### ISSUE THREAD

**Issue by devNaresh** [kodifitzwell/repo#18]
I have recently started using POV as my daily driver for video addon. I migrated from FEN and there it has one feature where a pop up would come to play next episode at the end of playing episode. Would that be possible to implement it here.

Something similar to -- https://github.com/im85288/service.upnext/wiki

**Comment by kodifitzwell** [comment]
does this setting not work that way?

![settings](https://github.com/kodifitzwell/repo/assets/105136042/a3c3b1cd-f40d-4698-bd24-c875cc384c5f)

**Comment by devNaresh** [comment]
Unfortunately  I am not getting these options. Here is the screenshot

![Screenshot 2024-04-20 212359](https://github.com/kodifitzwell/repo/assets/6941048/0369f80a-9862-4076-a77c-114f8a733b4c)

**Comment by kodifitzwell** [comment]
"Auto Play" must be enabled for that option to be visible.

**Comment by devNaresh** [comment]
Oh ok. Just one query, i want option to select source for next episode. Would it work, I am using tmdb helper player.

**Comment by kodifitzwell** [comment]
no idea about tmdhelper as I do not use it.  test and let us know.

>i want option to select source for next episode.

if "Autoplay Next Episode" is set you will see the pop up and the next episode will auto play.  this setting always overrides "Autoscrape Next Episode."

if you disable autoplay and keep "Autoscrape Next Episode" there is no window but the scrape will happen at the end of the episode.  I don't remember if the autoscrape happens if you manually stop the episode within the show window setting, I think it may.  the "trigger" uses the same show window setting for autoplay (even if it is disabled for autoscrape).

hopefully that makes sense.

there has been many discussions about autoplay/autospcrape/window/no window/default window action with regards to Fen.  it's my opinion at this time that the way it is currently is the compromise for all the different arguments made.

**Comment by devNaresh** [comment]
I did some testing and next episode pop up is working
