### ISSUE TITLE
BUG: Search Movies by Actor is broken in Dradis and Infinity

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#2]
Doing a search for an actor like Steve Martin returns random results. Many don't even list Steve Martin anywhere on IMDB. I also tested on another Venom based addons that I won't name and it also has this issue, so I did not attach a log, but I will if you need it.

BTW, the search works fine in POV

This is happening on another Venom clone that is active that I won't mentions, so maybe it's a baked in problem.

Running Kodi 21 on a ONN 4K Google TV box.

Thanks!

**Comment by kodifitzwell** [comment]
thanks for reporting it.  likely due to frequent changes at the imdb website because their desire to charge unreasonable amounts for api access.

for Dradis, I will likely change this to the tmdb api (POV uses tmdb I believe).  

even though they are both Venom based, rn I'm undecided what way I will change it for Infinity (for various reasons I won't name here).
