### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Hemicrusher** [kodifitzwell/repo#4]
First off, thanks for your hard work!

Two things I'd like to see, which would make Dradis easier to use for me. 

When looking through movies, like "Comedy" under Genres, I'll sometimes dig down multiple pages, and in order to get back to the "Discover Movie" or root section, I have to back up through each page. A context menu item like, "Back Home", or "Back to Movies" would make digging around easier. I know Fen Light and Umbrella have this option.

The other is, when using the same context menu to watch the trailer under "information", it would be quicker to access if "information" was at the top of the context menu. Or do something like Umbrella where there is a dedicated "Watch Trailer" menu item at the top of the list. This is not that big of a deal....just that I watch trailers more than the other menu items.

Anyhow, Thanks!

**Comment by kodifitzwell** [comment]
> A context menu item like, "Back Home", or "Back to Movies"

I have already implemented this, just haven't pushed the updated version yet.

> when using the same context menu to watch the trailer under "information"

information is not part of the Dradis context menu, I can't move it.  if you can get to this screen via a remote button (on a keyboard it is `i`) it is probably faster then using the contect menu.  I have an xbox 360 controller I use with my htpcs and this screen is mapped to a button.
![capture](https://github.com/kodifitzwell/repo/assets/105136042/852e1be6-3860-4648-bd26-8b65a38767c9)


> I watch trailers more than the other menu items.

are trailors always a youtube video?  a cursory look seems like tmdb returns yt videos in the metadata.  I see that the original Venom has the yt plugin as an "optional" requirement.  I have not bothered with looking into trailers from the cm yet because 1) I never watch trailers, 2) the yt api key seems like a hassle.  I have an idea of how I'd like to implement this if it is always a yt video.

**Comment by Hemicrusher** [comment]
Kodifitzwell

Looking forward to when the "Back Home" option....as for the trailers being YT, I don't think they are since the controls are different from when I use the Play Trailer menu in Umbrella, which I know does use YouTube.

Anyhow, thanks for the reply! Have a great weekend!

**Comment by Hemicrusher** [comment]
Kodifitzwell

Damn....that was fast!

Thank you!!!!!!!
