### ISSUE TITLE
Unable to browse show/season from widget (POV Addon)

### ISSUE THREAD

**Issue by bbviking** [kodifitzwell/repo#4]
I'm using the arctic horizon 2 skin and I'm unable to browse the show or season when I do it from a widget. If I attempt to do it from within the addon itself, then it seems to work fine.

I have attached a video of the behavior if that helps

https://github.com/kodifitzwell/repo/assets/20102131/ec980243-5fe5-4833-995a-42cf798b142c

**Comment by kodifitzwell** [comment]
in my video there is a set of context menu commands prefixed with POV and those work.  "Browse" opened the same as "Browse Season" because I have "Flatten Tv Show Seasons" set to "If Only One Season."

I installed AH2 just to see this.  I don't use any skin but the default, so this it isn't high on the priority list, but I will look into it when I have some time.

https://github.com/kodifitzwell/repo/assets/105136042/0c7d9914-2a5f-4d3a-b439-fd8a5e6075a8

**Comment by kodifitzwell** [comment]
I implemented the same code from the POV prefixed "browse" options into the non-prefixed options.  if this works please close the issue or lmk if unsuccessful.

**Comment by bbviking** [comment]
Thank you for the quick fix! I tested it now and that seems to work fine now
