### ISSUE TITLE
Possible episodes remaining bug

### ISSUE THREAD

**Issue by ivarbrandt** [kodifitzwell/repo#6]
Hey man, hope you're doing well.

I was working on updating my skin to support POV better and I ran across what might be a strange bug.

On the tvshow Seal Team, I have all episodes watched. However for some reason it shows "-1 remaining". As far as I know it's only happening on this show. Here's a screenshot:

![Screenshot_20240805-123508](https://github.com/user-attachments/assets/91536bbe-e9b8-4b74-ab7b-897940eb0407)

Here is the label and visibility condition that I use to display remaining episodes:

```
<label>$INFO[ListItem.Property(UnwatchedEpisodes),, remaining]</label>
<visible>
    Integer.IsGreater(ListItem.Property(WatchedEpisodes),0) + 
    !String.IsEqual(ListItem.Property(WatchedEpisodes),ListItem.Property(TotalEpisodes))
</visible>
```

If this isn't a bug, let me know and I'll code a solution around it.

**Comment by kodifitzwell** [comment]
hopefully this is due to trakt/tmdb mismatch.  trakt has one more episode because S4 has E1/E2 split into two maybe, where tmdb lists it as one episode.

[trakt seal team S4](https://trakt.tv/shows/seal-team/seasons/4)
[tmdb seal team S4](https://www.themoviedb.org/tv/71789-seal-team/season/4?language=en-US)

![sealteam](https://github.com/user-attachments/assets/2a1035bc-2eb1-4368-a45f-c8bf7a820dad)

how are you tracking watch status?  with trakt or internal to the addon?  I'm guessing trakt because then technically -1 is correct.

**Comment by ivarbrandt** [comment]
That explains it. Yeah I'm using Trakt. I'll code a workaround. Thanks for looking into this.
