### ISSUE TITLE
AfFENiity Adult Searches

### ISSUE THREAD

**Issue by JPM69** [kodifitzwell/repo#6]
Any chance you can add a setting to disable the adult xxx content from regular movie searches in AfFENity? If it's there already I can't seem to find it.
Thanks.

**Comment by kodifitzwell** [comment]
jpm6669 test the recently updated version `1.0.02e`, be sure to clear caches before you test if you do not clean install.

please return and close the issue if it is resolved.

there will be no "option" to turn adult results on, there are much better addons for adult content.

also, your beloved coalition is taken from a version of POV from last year.  it may not matter to you, but there have been many changes/fixes in POV.  mostly what was done with that coal is the few dozen image files were replaced with copies of the same image file instead of updating the code to point to a single image file.  so that coal is ~20mb of mostly the same image file.

**Comment by JPM69** [comment]
Thanks! I appreciate your understanding and fixing the search results. Also,  thanks for the info on my "beloved" coalition.  Lol. I plan on using AfFENity much more now that I know the search results won't be an issue for my little one to see.

I do appreciate all the hard work you developers do for us.
Thanks again and I will close this out.

**Comment by JPM69** [comment]
See above.  Thank you!
